accounts/urls.py
from django.urls import path

from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('users/<str:pk>/', views.users_detail, name='users_detail'),
    path('users/<str:pk>/profile_change/', views.profile_change, name='profile_change'),
    path('password_change/', views.password_change, name='password_change'),
    path('password_change/done/', views.password_change_done, name='password_change_done'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movieee.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movieee/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'movieee'
urlpatterns = [
    path('', views.index, name='index'),
    path('posts/new/', views.posts_new, name='posts_new'),
    path('posts/<int:pk>/', views.posts_detail, name='posts_detail'),
    path('posts/<int:pk>/edit/', views.posts_edit, name='posts_edit'),
    path('posts/<int:pk>/delete/', views.posts_delete, name='posts_delete'),
    path('posts/<int:pk>/comments_add/', views.comments_add, name='comments_add'),
]

accounts/models.py
import os
import uuid

from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import UserManager, PermissionsMixin
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.core.mail import send_mail
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


def get_file_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = '{}.{}'.format(uuid.uuid4(), ext)
    return os.path.join('icon', filename)


class CustomUserManager(UserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('The given email be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


# カスタムユーザー メールアドレスで認証
class CustomUser(AbstractBaseUser, PermissionsMixin):

    username_validator = UnicodeUsernameValidator()

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user_name = models.CharField(
        _('username'),
        max_length=30,
        help_text=_('この項目は必須です。半角数字、@/./+/-/_ で30文字以下にしてください。'),
        validators=[username_validator],
    )
    email = models.EmailField(
        _('email address'),
        unique=True,
        help_text=_('この項目は必須です。'),
    )
    icon = models.ImageField(_('アイコン'), upload_to=get_file_path, blank=True)

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = CustomUserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['user_name']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        return self.user_name

    def get_short_name(self):
        return self.user_name

    def email_user(self, subject, message, form_email=None, **kwargs):
        send_mail(subject, message, form_email, [self.email], **kwargs)

    @property
    def username(self):
        return self.email

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm

from .models import CustomUser


class SignupForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('email', 'user_name', 'password1', 'password2')


class ProfileForm(ModelForm):
    class Meta:
        model = CustomUser
        fields = ('email', 'user_name', 'icon')

accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import View, CreateView, TemplateView, UpdateView
from django.views.decorators.cache import never_cache

from .forms import SignupForm, ProfileForm
from .models import CustomUser


# カスタムログイン
class CustomLoginView(LoginView):
    template_name = 'accounts/login.html'

    def form_valid(self, form):
        auth_login(self.request, form.get_user())
        messages.success(self.request, 'ログインしました！')
        return HttpResponseRedirect(self.get_success_url())


login = CustomLoginView.as_view()


# カスタムログアウト
class CustomLogoutView(LogoutView):
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        auth_logout(request)
        next_page = self.get_next_page()
        if next_page:
            # Redirect to this page until the session has been cleared.
            messages.success(self.request, 'ログアウトしました！')
            return HttpResponseRedirect(next_page)
        return super().dispatch(request, *args, **kwargs)


logout = CustomLogoutView.as_view()


# 新規登録
class SignupView(CreateView):
    template_name = 'accounts/signup.html'
    form_class = SignupForm
    success_url = reverse_lazy('accounts:login')

    def form_valid(self, form):
        messages.success(self.request, '新規登録完了しました！')
        return super().form_valid(form)


signup = SignupView.as_view()


# ユーザー詳細表示
class UsersDetailView(View):
    def get(self, request, pk, *args, **kwargs):
        user = get_object_or_404(CustomUser, pk=pk)
        posts = user.post_set.all().order_by('-created_date')
        context = {
            'user': user,
            'posts': posts
        }
        return render(request, 'accounts/users_detail.html', context)


users_detail = UsersDetailView.as_view()


# パスワード変更
class CustomPasswordChangeView(PasswordChangeView):
    template_name = 'accounts/password_change_form.html'
    success_url = reverse_lazy('accounts:password_change_done')


password_change = CustomPasswordChangeView.as_view()


# パスワード変更完了
class CustomPasswordChangeDoneView(PasswordChangeDoneView):
    template_name = 'accounts/password_change_done.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        messages.success(self.request, 'パスワード変更完了！')
        return super().dispatch(*args, **kwargs)


password_change_done = CustomPasswordChangeDoneView.as_view()


# プロフィール変更
class ProfileChangeView(LoginRequiredMixin, UpdateView):
    model = CustomUser
    template_name = 'accounts/profile_change.html'
    form_class = ProfileForm

    def get_success_url(self):
        return reverse_lazy('accounts:users_detail', kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form):
        messages.success(self.request, 'プロフィールを更新しました！')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'プロフィールの更新に失敗しました')
        return super().form_invalid(form)


profile_change = ProfileChangeView.as_view()

templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}

<form method="post">{% csrf_token %}
    {% if form.errors %}
        <p>メールアドレスかパスワードが間違っています。もう一度入力してください。</p>
    {% endif %}
        <h2>ログイン</h2>
        <label>メールアドレス</label>
        <!-- LoginViewのform_class: AuthenticationFormがusername, modelsでusernameはすべてemail -->
        <input name="username">
        <br>
        <label>パスワード</label>
        <input type="password" name="password">
        <br>
    <input type="submit" value="ログイン" class="btn">
</form>

{% endblock %}

templates/accounts/password_change_done.html
{% extends 'base.html' %}
{% block content %}

<a href="{% url 'movieee:index' %}"><button class="btn">ホームに戻る</button></a>

{% endblock %}

templates/accounts/password_change_form.html
{% extends 'base.html' %}
{% block content %}

<h2>パスワード変更</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="パスワード変更" class="btn">
</form>

{% endblock %}

templates/accounts/profile_change.html
{% extends 'base.html' %}
{% block content %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="保存" class="btn">
</form>

{% endblock %}

templates/accounts/signup.html
{% extends 'base.html' %}
{% block content %}

<h2>ユーザー登録</h2>
<form action="{% url 'accounts:signup'%}" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="登録" class="btn">
</form>

{% endblock %}

templates/accounts/users_detail.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<h2 class="user-name">@{{ user.user_name }}</h2>
{% if user.icon %}
    <img class="icon" src="{{ user.icon.url }}" alt="icon">
{% else %}
    <img class="icon" src="{% static 'images/default-icon.svg' %}" alt="icon">
{% endif %}

{% if request.user == user %}
    <a href="{% url 'accounts:logout' %}"><button class="btn">ログアウト</button></a>
    <a href="{% url 'accounts:password_change' %}"><button class="btn">パスワード変更</button></a>
    <a href="{% url 'accounts:profile_change' user.id %}"><button class="btn">プロフィール変更</button></a>
{% endif %}

{% if posts.count != 0 %}
    <p>投稿<strong>{{ posts.count }}</strong>件</p>
{% else %}
    {% if user == request.user %}
        <p>初めての投稿をしてみましょう！</p>
    {% else %}
        <p>@{{ user.user_name }}さんはまだ投稿してません。</p>
    {% endif %}
{% endif %}
{% include 'movieee/post_list.html' %}

{% endblock %}