accounts/urls.py
from django.urls import path

from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('users/<str:pk>/', views.users_detail, name='users_detail'),
    path('users/<str:pk>/profile_change/', views.profile_change, name='profile_change'),
    path('password_change/', views.password_change, name='password_change'),
    path('password_change/done/', views.password_change_done, name='password_change_done'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movieee.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movieee/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'movieee'
urlpatterns = [
    path('', views.index, name='index'),
    path('posts/new/', views.posts_new, name='posts_new'),
    path('posts/<int:pk>/', views.posts_detail, name='posts_detail'),
    path('posts/<int:pk>/edit/', views.posts_edit, name='posts_edit'),
    path('posts/<int:pk>/delete/', views.posts_delete, name='posts_delete'),
    path('posts/<int:pk>/comments_add/', views.comments_add, name='comments_add'),
]

movieee/models.py
import os
import uuid

from django.db import models

from accounts.models import CustomUser


def get_file_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = '{}.{}'.format(uuid.uuid4(), ext)
    return os.path.join('image', filename)


class Post(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField()
    image = models.ImageField(upload_to=get_file_path, blank=True)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    comment = models.TextField()
    post = models.ForeignKey('movieee.Post', on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='users')
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment

movieee/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from .form import PostForm, CommentForm
from .models import Post, Comment
from django.views.generic import View, ListView, DetailView, CreateView, DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy


# 一覧表示
class IndexView(ListView):
    model = Post
    template_name = 'movieee/index.html'
    context_object_name = 'posts'

    def get_queryset(self):
        posts = Post.objects.all().order_by('-created_date')
        return posts

index = IndexView.as_view()


# 投稿詳細表示
class PostsDetailView(DetailView):
    model = Post
    template_name = 'movieee/posts_detail.html'

posts_detail = PostsDetailView.as_view()


# 投稿
class PostsNewView(LoginRequiredMixin, CreateView):
    model = Post
    template_name = 'movieee/posts_new.html'
    form_class = PostForm
    success_url = reverse_lazy('movieee:index')

    def form_valid(self, form):
        post = form.save(commit=False)
        post.user = self.request.user
        post.save()
        messages.success(self.request, 'レビューを投稿しました！')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'レビューの投稿に失敗しました！')
        return super().form_valid(form)

posts_new = PostsNewView.as_view()


# 削除
class PostsDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('movieee:index')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, 'レビューを削除しました')
        return super().delete(request, *args, **kwargs)

posts_delete = PostsDeleteView.as_view()


# 編集
class PostsEditView(LoginRequiredMixin, UpdateView):
    model = Post
    template_name = 'movieee/posts_edit.html'
    form_class = PostForm
    
    def get_success_url(self):
        return reverse_lazy('movieee:posts_detail', kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form):
        messages.success(self.request, 'レビューを更新しました！')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'レビューの更新に失敗しました')
        return super().form_invalid(form)

posts_edit = PostsEditView.as_view()


# コメント追加
class CommentsAddView(LoginRequiredMixin, View):
    def get(self, request, pk, *args, **kwargs):
        post = get_object_or_404(Post, pk=pk)
        context = {
            'form' : CommentForm()
        }
        return render(request, 'movieee/comments_add.html', context)

    def post(self, request, pk, *args, **kwargs):
        post = get_object_or_404(Post, pk=pk)
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.user = request.user
            comment.save()
        return redirect('movieee:posts_detail', pk=post.pk)
comments_add = CommentsAddView.as_view()

templates/movieee/comments_add.html
{% extends 'base.html' %}
{% block content %}

<h1>コメントの追加</h1>
<form method="post">{% csrf_token %}
    {{ form.as_p}}
    <button type="submit" class="btn">送信</button>
</form>

{% endblock %}

templates/movieee/index.html
{% extends 'base.html' %}
{% block content %}

{% include 'movieee/post_list.html' %}

{% endblock %}

templates/movieee/post_list.html
{% load static %}

<div class="posts-container">
    {% for post in posts %}
        <div class="post">
            <a href="{% url 'movieee:posts_detail' post.id %}">
                {% if post.image %}
                    <img src="{{ post.image.url }}" alt="{{ post.title}}_image">
                {% else %}
                    <img src="{% static 'images/no_image.png' %}" alt="{{ post.title}}_no_image">
                {% endif %}
            </a>
        </div>
    {% endfor %}
</div>

<!-- <div class="post-container">
    {% for post in posts %}
        <div class="post">
            <div class="post-title">
                <p><strong>{{ post.title|truncatechars_html:20 }}</strong></p>
            </div>
            <a href="{% url 'movieee:posts_detail' post.id %}">
                {% if post.image %}
                    <img src="{{ post.image.url }}" class="post-img">
                {% else %}
                    <img src="{% static 'images/no_image.png' %}" alt="post-detail" class="post-img">
                {% endif %}
            </a>
            <div class="post-text">
                <p>{{ post.text|truncatechars_html:25 }}</p>
            </div>
            <div class="post-info">
                <a href="{% url 'accounts:users_detail' post.user.id %}" class="post-user">@{{ post.user.user_name }}</a>
                <div class="post-date">
                    <p>{{ post.created_date|date:"Y/m/d H:i" }}</p>
                </div>
            </div>
        </div>
    {% endfor %}
</div> -->

templates/movieee/posts_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="action">
    {% if request.user == post.user %}
        <a href="{% url 'movieee:posts_edit' post.id %}" method="post" class="edit">
            <button class="btn" type="submit">編集</button>
        </a>
        <form action="{% url 'movieee:posts_delete' post.id %}" method="post" class="delete">{% csrf_token %}
            <button class="btn" type="submit" onclick='return confirm("本当に削除しますか？");'>削除</button>
        </form>
    {% endif %}
</div>

<div class="post-detail">
    {% if post.image %}
        <img src="{{ post.image.url }}" alt="post-detail" class="post-img">
    {% else %}
        <img src="{% static 'images/no_image.png' %}" alt="post-detail" class="post-img">
    {% endif %}
    <div class="post-main">
        <h2>{{ post.title }}</h2>
        <div class="post-info">
            <a href="{% url 'accounts:users_detail' post.user.id %}" class="post-user">@{{ post.user.user_name }}</a>
            <div class="post-date">
                <p>{{ post.created_date|date:"Y/m/d H:i" }}</p>
            </div>
        </div>
        <hr>
        <p>{{ post.text|linebreaksbr }}</p>
    </div>
</div>

<hr>
<div class="comment-container">
    <a href="{% url 'movieee:comments_add' post.id %}"><button class="btn" type="submit">コメントする</button></a>
    <h3>コメント一覧</h3>
    {% for comment in post.comments.all %}
        <div class="comment">
            <div class="comment-date">
                <p>{{ comment.created_date|date:"Y/m/d H:i" }}</p>
            </div>
            <a href="{% url 'accounts:users_detail' comment.user.id %}" class="comment-user">
                <strong>@{{ comment.user }}</strong>
            </a>
            <p>{{ comment.comment|linebreaks }}</p>
        </div>
    {% empty %}
        <p>No comments here yet</p>
    {% endfor %}
</div>

{% endblock %}

templates/movieee/posts_edit.html
{% extends 'base.html' %}
{% block content %}

<div>
    <a href="{% url 'movieee:posts_detail' post.id %}">
        <button class="btn" type="submit">戻る</button>
    </a>
</div>

<form action="{% url 'movieee:posts_edit' pk=form.instance.pk %}" method="post" enctype="multipart/form-data">{% csrf_token %}
    {% include 'movieee/posts_form.html' %}
</form>

{% endblock %}

templates/movieee/posts_form.html
<table>
    <tr>
        <th>タイトル</th>
        <td>{{ form.title }}</td>
    </tr>
    <tr>
        <th>内容</th>
        <td>{{ form.text }}</td>
    </tr>
    <tr>
        <th>画像</th>
        <td>{{ form.image }}</td>
    </tr>
</table>
<button type="submit" class="btn">投稿</button>

templates/movieee/posts_new.html
{% extends 'base.html' %}
{% block content %}

<div>
    <a href="{% url 'movieee:index' %}">
        <button class="btn" type="submit">ホームに戻る</button>
    </a>
</div>

<form action="{% url 'movieee:posts_new' %}" method="post" enctype="multipart/form-data">{% csrf_token %}
    {% include 'movieee/posts_form.html' %}
</form>

{% endblock %}