accounts/urls.py
from django.urls import path

from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('users/<str:pk>/', views.users_detail, name='users_detail'),
    path('users/<str:pk>/profile_change/', views.profile_change, name='profile_change'),
    path('password_change/', views.password_change, name='password_change'),
    path('password_change/done/', views.password_change_done, name='password_change_done'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movieee.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movieee/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'movieee'
urlpatterns = [
    path('', views.index, name='index'),
    path('posts/new/', views.posts_new, name='posts_new'),
    path('posts/<int:pk>/', views.posts_detail, name='posts_detail'),
    path('posts/<int:pk>/edit/', views.posts_edit, name='posts_edit'),
    path('posts/<int:pk>/delete/', views.posts_delete, name='posts_delete'),
    path('posts/<int:pk>/comments_add/', views.comments_add, name='comments_add'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Movieee</title>
        <link href="https://fonts.googleapis.com/css?family=Lobster&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>
    <body>
        <div class="container">
            <header>
                <h1><a href="{% url 'movieee:index' %}" class="logo">Movieee</a></h1>
                <nav>
                    <ul class="menu">
                        <li><a href="{% url 'movieee:posts_new' %}">投稿</a></li>
                        {% if request.user.is_authenticated %}
                            <li><a href="{% url 'accounts:users_detail' request.user.id %}">マイページ</a></li>
                        {% else %}
                            <li><a href="{% url 'accounts:login' %}">ログイン</a></li>
                        {% endif %}
                    </ul>
                </nav>
            </header>
            <main>
                {% for message in messages %}
                    <p class="message-success">{{ message }}</p>
                {% endfor %}
                {% block content %}{% endblock %}
            </main>
            <footer></footer>
        </div>
    </body>
</html>